### ISSUE TITLE
Landing page live data cards last update indicators meaning is unclear

### ISSUE THREAD

**Issue by marklinnane** [LiamOSullivan/bcd-dd-v2#41]
They may be read as standard clocks

**Comment by LiamOSullivan** [comment]
Indicators changed to age of data displays with commit 1594e786d80852168f1539ff970bd3d6d3f3a996

**Comment by marklinnane** [comment]
Bikes and Motorway are good. Still have issues with Weather Forecast which uses the same method as other cards but refers to the future. Inconsistency feels like dashboard is not working properly, particularly when the other absolute time clock on the page has a different time.
