### ISSUE TITLE
Landing Page Property Price card links to incorrect page position

### ISSUE THREAD

**Issue by marklinnane** [LiamOSullivan/bcd-dd-v2#49]
Section title is out of view.
<img width="1792" alt="Screenshot 2019-05-31 at 16 35 03" src="https://user-images.githubusercontent.com/9986106/58717051-479ee300-83c2-11e9-9a1b-5d22caf6c90a.png">

**Comment by LiamOSullivan** [comment]
Fixed commit 6900847bdd8cc17b5594f7ce555a980e5affdc43
