### ISSUE TITLE
Themes>Employment charts not displaying correctly

### ISSUE THREAD

**Issue by LiamOSullivan** [LiamOSullivan/bcd-dd-v2#97]
If button is pressed to switch between chart types, chart does not display until window is resized.

<img width="530" alt="Screen Shot 2019-07-05 at 16 42 42" src="https://user-images.githubusercontent.com/3306019/60733169-00b58780-9f44-11e9-9871-346902d08429.png">

**Comment by BashirShalaik** [comment]
I will work on it today Monday the 08 of July
